@startuml board
'https://plantuml.com/state-diagram

state Доска{
    [*] --> Редактирование_доски : Кнопка редактирования нажата
    [*] --> Список_задач
    state Редактирование_доски{
        [*] --> Ввод_нового_названия
        [*] --> Изменение_участников_доски
    }
    state Список_задач{
        state Задача{
            [*]-->Выпадающий_список_статусов_задачи : Выбрано новое значение из выпадающего\nсписка статусов задачи нажата
            [*]-->Редактирование_задачи : Кнопка редактирования нажата
            [*] --> Создание_задачи : Кнопка создания нажата
            state Редактирование_задачи{
                [*] --> Изменение_названия_задачи
                Изменение_названия_задачи --> Изменение_описания
                Изменение_описания --> Изменение_продолжительности_задачи
                Изменение_продолжительности_задачи -->Изменение_колличечства_поинтов_за_задачу
                Изменение_колличечства_поинтов_за_задачу -->Измение_дедлайнов
                Измение_дедлайнов --> Измение_исполнителя
                Измение_исполнителя --> Измение_статуса_публичности_или_открытую_задачу
                Измение_статуса_публичности_или_открытую_задачу --> Изменение_медиаматериалов
                Изменение_медиаматериалов --> Завершение_редактирования : Кнопка сохранить нажата
            }
            state Создание_задачи{
                [*] --> Ввод_названия_задачи
                Ввод_названия_задачи --> Ввод_описания
                Ввод_описания --> Ввод_продолжительности_задачи
                Ввод_продолжительности_задачи -->Ввод_колличечства_поинтов_за_задачу
                Ввод_колличечства_поинтов_за_задачу -->Выбор_дедлайнов
                Выбор_дедлайнов --> Выбор_исполнителя
                Выбор_исполнителя --> Переключение_на_скрытую_или_открытую_задачу
                Переключение_на_скрытую_или_открытую_задачу --> Добавление_медиаматериалов
                Добавление_медиаматериалов --> Завершение_создания : Кнопка создания нажата
            }
        }
    }
    Ввод_нового_названия --> [*]
    Изменение_участников_доски --> [*]
    Выпадающий_список_статусов_задачи --> [*]
    Завершение_редактирования --> [*]
    Завершение_создания --> [*]
}

@enduml