@startuml chats
'https://plantuml.com/state-diagram
state Страница_Чатов{
    state Список_Чатов{
        Нажатие_на_чат --> Страница_Чата
    }
    state Кнопка_создания_чата{
        [*] --> Диалоговое_окно_создания_чата
        state Диалоговое_окно_создания_чата{
            [*] -down-> Выбор_участников
            Выбор_участников -down-> Ввод_названия_чата
        }
    }
    Ввод_названия_чата --> [*]

}
state Страница_Чата{
}
@enduml