@startuml chat
'https://plantuml.com/state-diagram

state Страница_Чата{
    
    [*] --> Окно_ввода_текста
    Окно_ввода_текста --> Кнопка_отправки_сообщения
    Кнопка_отправки_сообщения --> [*]
}

@enduml