@startuml login
'https://plantuml.com/state-diagram



state Стартовый_экран {
  [*] --> Ввод_логина
  Ввод_логина -> Ввод_пароля
  Ввод_пароля --> Войти
  Войти ---> Домашняя_страница : [Логин и пароль верные]
  Войти -> Сообщение_об_ошибке : [Логин или пароль неверные]
  Сообщение_об_ошибке -> Ввод_логина

}

state Домашняя_страница{
}

@enduml