@startuml navBar


'https://plantuml.com/state-diagram

state Панель_Навигации{
    Иконка_Домашней_Страницы --> Домашняя_Страница : Нажатие на иконку
    Иконка_Чатов --> Страница_Чатов : Нажатие на иконку
    Иконка_Досок --> Страница_Досок_Компании : Нажатие на иконку
    Иконка_Настроек --> Страница_Настроек: Нажатие на иконку
}
state Домашняя_Страница{

}
state Страница_Чатов{

}
state Страница_Досок_Компании{

}
state Страница_Настроек{

}

@enduml