@startuml settings
'https://plantuml.com/state-diagram

state Страница_Настроек{
    
    [*] -->  Выпадающий_список_языков : Выбран язык
    [*]-->Выход_из_приложения : Кнопка выхода нажата

    Выпадающий_список_языков --> [*]
    Выход_из_приложения --> [*]
}

@enduml