@startuml settings
'https://plantuml.com/state-diagram

state Страница_Настроек{
    
    [*] -->  Выпадающий_список_языков 
    [*]-->Выход_из_приложения : Кнопка выхода нажата

    
    Выход_из_приложения --> Страница_авторизации
    Выпадающий_список_языков --> [*] : Выбран язык
    Страница_авторизации --> [*]
}

@enduml