@startuml components
'https://plantuml.com/component-diagram


component "Клиентское приложение" {
  [Пользовательский интерфейс]
  [Логический слой]
  [Слой хранилища]
  [Запросы]
}

component "Сервер" {

   component "Балансировщик нагрузки" {
      [Nginx]
   }

   component "Docker Оркестратор"{
   
      node "Обратный прокси"{
         [Nginx Container]
      }

      node "Серверное приложение" {
         [Контроллер]
         [API взаимодействия с базой данных]
      }

      database "База данных" {
         [Обработчик]  
      }

      node "Front контейнер"{
         [Web-приложение]
      }
   }
}



[Пользовательский интерфейс] - [Логический слой]
[Логический слой] - [Слой хранилища]
[Логический слой] -- [Запросы]
[Запросы] --> [Nginx]
[Nginx] --> [Nginx Container]
[Nginx Container] <-down-> [Контроллер]
[Nginx Container] <--> [Web-приложение]
[Контроллер] -- [API взаимодействия с базой данных]
[API взаимодействия с базой данных] <--> [Nginx Container]
[Nginx Container] <-up-> [Обработчик]


@enduml