@startuml components
'https://plantuml.com/component-diagram


component "Клиент" {
  [Пользовательский интерфейс]
  [Логический слой]
  [Слой хранилища]
  [Запросы]
}

node "Сервер" {
  [Контроллер]
  [API взаимодействия с базой данных]
}

database "База данных" {
  [Обработчик]
  folder "Пользователи" {
    [Идентификатор П]
    [Никнейм]
    [Логин]
    [Пароль]
    [Уведомления по почте]
    [Пуш уведомления]
    [Пуш токены]
  }
  folder "Доски" {
     [Идентификатор Д]
     [Название Д]
  }
  folder "Карточки" {
     [Идентификатор К]
     [Название К]
     [Описание К]
     [Состояние К]
     [Длительность К]
     [Баллы]
     [Ссылки]
     [Заметки]
     [Скрыта]
     [Дата время начала]
     [Дата время закрытия]
     [Идентификатор доски К]
     [Идентификатор автора]
     [Идентификатор исполнителя]     
  }
  folder "Заметки"{
     [Идентификатор З]
     [Текст З]
     [Идентификатор автора З]
  }
  folder "Чат"{
     [Идентификатор Ч]
     [Название Ч]
     [Приватность]
  }
  folder "История"{
     [Идентификатор И]
     [Идентификатор чата И]
     [Идентификатор пользователя И]
     [Текст З]
     [UTC время]
     [Идентификатор карточки И]
     [Идентификатор доски И]
  }  
  folder "Чат/Пользователь"{    
     [Идентификатор чата ЧП]
     [Идентификатор пользователя ЧП]     
  }
  folder "Доска/пользователь"{
    [Идентификатор доски ДП]
    [Идентификатор пользователя ДП]
  }  
}

[Пользовательский интерфейс] - [Логический слой]
[Логический слой] - [Слой хранилища]
[Логический слой] -- [Запросы]
[Запросы] --> [Контроллер]
[Контроллер] -- [API взаимодействия с базой данных]
[API взаимодействия с базой данных] --> [Обработчик]
[Идентификатор пользователя И] -left-> [Идентификатор П]
[Идентификатор чата И]-left->[Идентификатор Ч]
[Идентификатор чата ЧП]-->[Идентификатор Ч]
[Идентификатор пользователя ЧП]-->[Идентификатор П]
[Идентификатор доски ДП]-up->[Идентификатор Д]
[Идентификатор пользователя ДП]-up->[Идентификатор П]
[Идентификатор автора]-up-->[Идентификатор П]
[Идентификатор исполнителя]-up-->[Идентификатор П]
[Идентификатор карточки И]-->[Идентификатор К]
[Идентификатор доски И]-->[Идентификатор Д]
[Идентификатор доски К]-up->[Идентификатор Д]

@enduml