@startuml deployment
'https://plantuml.com/deployment-diagram

actor Пользователь

agent Мобильное_приложение
agent Веб_приложение


database База_данных

node Сервер

Пользователь --> Мобильное_приложение
Пользователь --> Веб_приложение
Веб_приложение <--> Сервер
Мобильное_приложение <--> Сервер
Сервер <-> База_данных

@enduml