@startgantt gant
'https://plantuml.com/gantt-diagram

printscale weekly zoom 3
language ru
Project starts 2023-02-12

[Разработка архитектуры\nприложения] as [PLAN] lasts 16 days and is colored in White/Black
[Разработка UX] as [UX] lasts 9 days
[Разработка архитектуры\nклиент-сервера] as [CS] lasts 11 days and is colored in Lavender/LightBlue
[Выбор стека технологий] as [CST] lasts 6 days and is colored in LightGreen/LightBlue

[Разработка UI] as [UI] lasts 11 days and is colored in White/Black and starts at 2023-02-17
[Выбор направления дизайна] as [DES] lasts 5 days and is colored in Lavender/LightBlue
[Разработка UI в FIGMA] as [FIGMA] lasts 9 days and is colored in Lavender/LightBlue
[Написание UI] as [VERST] lasts 13 days and is colored in Lavender/LightBlue

[Тестирование UI] as [UIT] starts at 2023-03-11  and lasts 12 days and is colored in LightGrey/Black
[Доработка UI] as [UIR] lasts 12 days and is colored in Grey/Black

[Разработка модуля\nвзаимодействия с API] as [MAPI] lasts 15 days and is colored in White/Black and starts at 2023-03-23
[Разработка запросов API] as [REQ] lasts 11 days and is colored in Lavender/LightBlue
[Разработка моделей данных] as [MODEL] lasts 13 days and is colored in Lavender/LightBlue
[Разработка модуля локального хранилища] as [STOR] lasts 10 days and is colored in Lavender/LightBlue

[Тестрирование модуля API] as [TAPI] lasts 12 days and is colored in LightGrey/Black and starts at 2023-04-23
[Доработка модуля API] as [DAPI] lasts 12 days and is colored in Grey/Black

[Разработка модуля коннектора UI с\nмодулем взаимодействия с API] as [LOGIC] lasts 15 days and is colored in White/Black and starts at 2023-05-01

[Тестрирование коннектора] as [TLOGIC] lasts 10 days and is colored in LightGrey/Black and starts at 2023-05-14
[Доработка коннектора] as [DLOGIC] lasts 10 days and is colored in Grey/Black

[Тестрирование прототипа] as [TPROT] lasts 12 days and is colored in LightGrey/Black and starts at 2023-05-23
[Доработка прототипа] as [DPROT] lasts 12 days and is colored in Grey/Black

[Внедрение и подготовка к запуску] starts at 2023-06-04


[UX] is colored in Lavender/LightBlue and starts at [PLAN]`s start
[CS] starts 3 days after [PLAN]`s start
[CST] starts 8 days after [PLAN]`s start

[UI] starts at 2022-10-11
[DES] starts at [UI]`s start
[FIGMA] starts 3 days after [UI]`s start
[VERST] starts 9 days after [UI]`s start

[REQ] starts at [MAPI]`s start
[MODEL] starts 11 days after [MAPI]`s start
[STOR] starts 22 days after [MAPI]`s start
[UIT] starts at [UIR]`s start
[UIR] ends at [UIT]`s end

[TAPI] starts at 2022-11-11 and starts at [DAPI]`s start
[DAPI] ends at [TAPI]`s end

[TLOGIC] starts at 2022-12-1 and starts at [DLOGIC]`s start
[DLOGIC] ends at [TLOGIC]`s end

[TPROT] starts at 2022-12-6 and starts at [DPROT]`s start
[DPROT] ends at [TPROT]`s end



@endgantt