// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2onuL4-UEGa8xDziv5-ZevBXMx5f_p8s',
    appId: '1:285417917451:web:5ced8713fd9eb3c4010b0e',
    messagingSenderId: '285417917451',
    projectId: 'sbeutasklet',
    authDomain: 'sbeutasklet.firebaseapp.com',
    storageBucket: 'sbeutasklet.appspot.com',
    measurementId: 'G-EPT0HJEFSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlowQF2HaK8crW-eu9EoslFL54kER6GwY',
    appId: '1:285417917451:android:a8aaf9148a1e9169010b0e',
    messagingSenderId: '285417917451',
    projectId: 'sbeutasklet',
    storageBucket: 'sbeutasklet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeeo51QsPBKagD_hfCxfbu6oaWA7NjTBM',
    appId: '1:285417917451:ios:9c1ccbde34cc6516010b0e',
    messagingSenderId: '285417917451',
    projectId: 'sbeutasklet',
    storageBucket: 'sbeutasklet.appspot.com',
    iosClientId: '285417917451-d85plkjeoatidcte2paaa8hpd2a3q3aj.apps.googleusercontent.com',
    iosBundleId: 'com.sbeu.tasklet.newprojname',
  );
}
