@startuml creatingTask
'https://plantuml.com/activity-diagram-beta

|C1| Сотрудник создающий задачу
|С2| Сотрудник, которому назначена задача
|C1|
start
    :Выбор доски с задачами<
    :Нажатие кнопки\n'создания новой задачи'<
    :Создание новой задачи|
    :Ввод названия задачи<
    :Ввод описания задачи<
    :Ввод продолжительности задачи<
    :Ввод количества поинтов за задачу<
    :Добавление медиаматериалов к задаче<
    :Ввод дедлайнов задачи<
    :Выбор исполнителя<
    :Нажатие кнопки 'создать'<
    |С2|
    :Получение почтового уведомления о новой задаче>
    :Получен пуш уведомления о новой задаче>
end



@enduml
