@startuml send
'https://plantuml.com/activity-diagram-beta
|С2| Другие сотрудники в чате
|С1| Сотрудник отправляющий сообщение

start
    :Открытие чата<
    :Ввод текста сообщения\nв поле ввода<    
    :Нажатие кнопки отправки сообщения<
    :Отправка сообщения|
    :Отправка уведомления\nдругим сотрудникам чата>
    |С2|
    :Получение уведомления\nо новом сообщении<
stop

@enduml
