@startuml editingTask
'https://plantuml.com/activity-diagram-beta

|C1| Сотрудник меняющий статус задачи
|С2| Сотрудники, которые участвуют в задаче
|C1| 
start
    :Выбор нового статуса для задачи<    
    |С2|
    :Получение почтового уведомления о том, что статус задачи изменился>
    :Получение пуш уведомления о том, что статус задачи изменился>
end



@enduml
